### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by obtim** [infinitelytight/mma-elo#1]
Traceback (most recent call last):
  File "scrape.py", line 105, in <module>
    np.savetxt("results.csv", results, delimiter=";", fmt="%s")
  File "<__array_function__ internals>", line 5, in savetxt
  File "C:\Users\obtim\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\lib\npyio.py", line 1452, in sa
vetxt
    fh.write(v)
  File "C:\Users\obtim\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0301' in position 3: character maps to <undefined>

and please add requirements.txt to repo

**Comment by nandzi** [comment]
Hey, which platform are you using? I've tested this program only on Linux and I think this is a Windows encoding error. The character '\u0301' is an accent, as in the name Gutiérrez. From what I understand the Windows terminal doesn't support Unicode so printing fails. You can try [fixing this](https://wiki.python.org/moin/PrintFails) first... if it still doesn't work then it could be that numpy (the function `np.savetxt`) is also struggling with Unicode characters, but this doesn't seem to be a problem on Linux.

The requirements are just Python 3, the libraries used in the `scrape.py` file (BeautifulSoup, numpy, etc.), and basic R (for running `Rscript mma.R`) - no extra R packages needed. When I have time I'll update the rankings and try to write more complete instructions.
